### PR TITLE
Changed handling of transient kube apiserver errors

### LINKED ISSUE #260: Kubernetes: do not switch back the health check to false when failing to load Ingress resources
We should never toggle back the health check to `false` in case of transient Kubernetes errors, as this would remove the node from the load balancer. The current behavior will disable all apps if the API server is temporary unavailable (e.g. because of etcd problems).

Only this `if` needs to be removed: https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/kube.go#L347

### PR DESCRIPTION
**Pull request by Raffo**
Closes #260.

### CODE REVIEW

**Comment by lmineiro** [comment]
@aryszka should confirm that returning err to the routing handler will keep old routing table

**Comment by lmineiro** [comment]
lgtm

**Comment by Raffo** [comment]
Tests failing, nice! On it.

**Comment by aryszka** [comment]
@lmineiro @Raffo "err to the routing handler will keep old routing table": correct

File: dataclients/kubernetes/kube_test.go [hunk 1]
```diff
@@ -855,10 +855,10 @@ func TestHealthcheckInitial(t *testing.T) {
 
 		r, err := dc.LoadAll()
 		if err != nil {
```
Comment (aryszka) [inline dataclients/kubernetes/kube_test.go]: i think here we want to test if we actually have an error, so i recommend something like this:

```
if err == nil {
    t.Error("error expected")
}
```

and the call to `checkHealthCheck` is unnecessary from that point

File: dataclients/kubernetes/kube_test.go [hunk 2]
```diff
@@ -987,15 +987,15 @@ func TestHealthcheckReload(t *testing.T) {
 			ProvideHealthcheck: true,
 		})
 
-		dc.LoadAll()
+		prevr, _ := dc.LoadAll()
 		api.failNext = true
 
 		r, err := dc.LoadAll()
 		if err != nil {
-			t.Error("failed to fail")
```
Comment (aryszka) [inline dataclients/kubernetes/kube_test.go]: similarly to my other comment.

Actually, i think the tests "use healthcheck, fail" and "use healthcheck, reload fail" are not necessary anymore because they were testing a behavior that was removed. At least we can fix something by purely removing code :)

File: dataclients/kubernetes/kube_test.go (hunk 1 above)
Comment (aryszka) [inline dataclients/kubernetes/kube_test.go]: better delete "use healthcheck, fail" and "use healthcheck, reload fail" tests. See the explanation in the other comment.

File: dataclients/kubernetes/kube_test.go (hunk 2 above)
Comment (Raffo) [inline dataclients/kubernetes/kube_test.go]: Ok, then I can remove them.

**Comment by hjacobs** [comment]
:+1:
