### PR TITLE
fix: 2852 unspecified addresses should fail

### LINKED ISSUE #2852: ClientIP predicate is giving inconsistent results
**Describe the bug**
[FuzzClientIP](https://github.com/zalando/skipper/pull/2846/files#diff-84e4882219d180a437d9fff5d2316ba969545913914487f865a79c87096b2d00) fuzz target found an inconsistency in [ClientIP](https://opensource.zalando.com/skipper/reference/predicates/#clientip) predicate where the Predicate doesn't match for the same value.

the fuzzer panics when the ip address is `::`

**To Reproduce**
apply the following patch:
```diff
diff --git a/predicates/source/source_test.go b/predicates/source/source_test.go
index e52efac8..d77bda80 100644
--- a/predicates/source/source_test.go
+++ b/predicates/source/source_test.go
@@ -299,6 +299,11 @@ func TestMatchingClientIP(t *testing.T) {
                []interface{}{"C0:FF::EE/127"},
                &http.Request{RemoteAddr: "[C0:FF::EC]:1234"},
                false,
+       }, {
+               "invalid case",
+               []interface{}{"::"},
+               &http.Request{RemoteAddr: "::"},
+               true,
        }} {
                t.Run(ti.msg, func(t *testing.T) {
                        pred, err := (&spec{typ: clientIP}).Create(ti.args)
   
```

then run `go test` in the `predicates/source`

**Expected behavior**
ClientIP must provide consistent results

### PR DESCRIPTION
**Pull request by szuecs**
fix #2852

### CODE REVIEW

File: net/net.go [hunk 1]
```diff
@@ -144,6 +144,8 @@ func ParseIPCIDRs(cidrs []string) (*netipx.IPSet, error) {
 
 		} else if addr, err := netip.ParseAddr(w); err != nil {
 			return nil, err
+		} else if addr.IsUnspecified() {
+			return nil, fmt.Errorf("failed to parse cidr: addr is unspcified: %s", w)
```
Comment (AlexanderYastrebov) [inline net/net.go:148]: typo `unspecified`

Comment (szuecs) [reply net/net.go]: fixed

**Comment by MustafaSaber** [comment]
👍
