### PR TITLE
Eskip check fails on empty URL on network backend.

### LINKED ISSUE #2523: eskip check don't fail when backend is empty string
**Describe the bug**
`eskip check routes.eskip` don't fail if there's a route with backend is an empty string but `skipper -routes-file routes.eskip ` fails with the message `failed to process route foo: parse "": empty url `

**To Reproduce**
Using image base `registry.opensource.zalan.do/teapot/skipper:v0.16.67`  executing `eskip check routes.eskip` there's no failure.

Executing `skipper -routes-file test.eskip`
> [APP]INFO[0000] Expose metrics in codahale format            
> [APP]INFO[0000] enable swarm: false                          
> [APP]INFO[0000] Replacing tee filter specification           
> [APP]INFO[0000] Replacing teenf filter specification         
> [APP]INFO[0000] Replacing lua filter specification           
> [APP]INFO[0000] support listener on :9911                    
> [APP]INFO[0000] Dataclients are updated once, first load complete 
> [APP]INFO[0000] Listen on :9090                              
> [APP]INFO[0000] route settings, reset, route: foo: Path("/foo") -> setPath("/") -> "" 
> [APP]INFO[0000] route settings, reset, route: bar: Path("/bar") -> setPath("/") -> "https://bar.example.org/" 
> [APP]INFO[0000] route settings received                      
> **[APP]ERRO[0000] failed to process route foo: parse "": empty url** 
> [APP]INFO[0000] route settings applied                       
> [APP]INFO[0000] TLS settings not found, defaulting to HTTP 

`routes.eskip` file content 

> foo: Path("/foo") -> setPath("/") -> ""
> bar: Path("/bar") -> setPath("/") -> "https://bar.example.org/" 

**Expected behavior**
Consistent behaviour between `eskip` and `skipper`, if `skipper` fails loading routes with empty backend then `eskip` should also fail

**Observed behavior**

### PR DESCRIPTION
**Pull request by xavivars**
This change to `eskip check` validates no routes have empty backend. 

"empty url" error falls between the "_pure syntactical_" checks that `eskip check` runs at validation time and the "_route-specific setup-dependant_" checks that skipper does at runtime (making sure, for example, that all predicates / filters exist, etc).

While this is not a fatal error, and loading the skip files in skipper works (only the specific route gets discarded), we think having this validation in `eskip check` is a better approach, because this is an error that is known in advance (no URL can be empty) and we could not find a reason we'd ever want to, on purpose, push a non-working route to production.

 Fixes #2523

### CODE REVIEW

File: cmd/eskip/load.go [hunk 1]
```diff
@@ -103,9 +103,26 @@ func checkCmd(a cmdArgs) error {
 		return err
 	}
 
+	err = checkEmptyBackends(routes)
+
```
Comment (AlexanderYastrebov) [inline cmd/eskip/load.go:107]: No need to have a blank line inbetween

File: cmd/eskip/load.go [hunk 2]
```diff
@@ -103,9 +103,26 @@ func checkCmd(a cmdArgs) error {
...
+	}
+
 	return checkRepeatedRouteIds(routes)
 }
 
+func checkEmptyBackends(routes []*eskip.Route) error {
+
+	for _, route := range routes {
+		if route.BackendType == eskip.NetworkBackend && route.Backend == "" {
+			return errors.New("Route has empty backend: " + route.Id)
```
Comment (AlexanderYastrebov) [inline cmd/eskip/load.go:119]: fmt.Errorf would be cleaner

File: cmd/eskip/load.go [hunk 3]
```diff
@@ -103,9 +103,26 @@ func checkCmd(a cmdArgs) error {
...
+
+	if err != nil {
+		return err
+	}
+
 	return checkRepeatedRouteIds(routes)
 }
 
+func checkEmptyBackends(routes []*eskip.Route) error {
+
```
Comment (AlexanderYastrebov) [inline cmd/eskip/load.go:116]: Please drop blank lines

File: cmd/eskip/load.go (hunk 2 above)
Comment (AlexanderYastrebov) [reply cmd/eskip/load.go:119]: Error message should start from lower case (I know you've copied this from checkRepeatedRouteIds)

File: cmd/eskip/load_test.go [hunk 4]
```diff
@@ -142,6 +142,20 @@ func TestCheckRepeatingRouteIds(t *testing.T) {
 	}
 }
 
+func TestCheckEmptyBackend(t *testing.T) {
+	const name = "testFile"
+	err := withFile(name, `foo: Method("POST") -> "https://www.example1.org";empty: Method("POST") -> "";`, func(_ *os.File) {
+		err := checkCmd(cmdArgs{in: &medium{typ: file, path: name}})
+		if err == nil {
+			t.Error("Expected an error for empty backend")
+		}
```
Comment (AlexanderYastrebov) [inline cmd/eskip/load_test.go:151]: Lets check specific error value here.

**Comment by AlexanderYastrebov** [comment]
Thank you. 
I think we can have it like you propose (after comments are addressed).

In general I think we should make backed validation more strict during eskip parsing - then k8s dataclient and webhook would benefit from it as well. @MustafaSaber is working on validation topic, see related https://github.com/zalando/skipper/issues/1618

File: cmd/eskip/load.go (hunk 2 above)
Comment (xavivars) [reply cmd/eskip/load.go:119]: Do you want me to also fix the ones in `checkRepeatedRouteIds`? To me, it makes little sense to have different ways of formatting errors few lines apart...

File: cmd/eskip/load_test.go (hunk 4 above)
Comment (xavivars) [reply cmd/eskip/load_test.go:151]: Do you mean something like `if err == nil || !errors.Is(err, expectedError) ` ?

Comment (AlexanderYastrebov) [reply cmd/eskip/load_test.go:151]: No, just something like `if err == nil || err.Error() != "route has empty backend: empty"`

File: cmd/eskip/load.go (hunk 2 above)
Comment (AlexanderYastrebov) [reply cmd/eskip/load.go:119]: Yes, please fix another case

**Comment by xavivars** [comment]
Thanks for the quick review!

I think I've addressed all your comments now.

And I agree: stricter backend validation would be great.

**Comment by AlexanderYastrebov** [comment]
Thank you.

**Comment by szuecs** [comment]
:+1:
