### PR TITLE
fix: proxy filter panics did not run applyFiltersOnError

### LINKED ISSUE #3966: filters that were processed on request should be called in response if there was a filter panic
If you have a filter chain:

```
a() -> b() 
```

a() is a scheduler filter like fifo/lifo that implements the proxy internal `errorHandlerFilter interface`:
```
func (f *fifoFilter) HandleErrorResponse() bool {
	return true
}
```

If b() panics we do not execute a() even if we should, because a() was processed correctly.
This can lead to weir behavior that you get panics but then you are also getting errors caused by filter a() for example.

### PR DESCRIPTION
**Pull request by szuecs**
fix https://github.com/zalando/skipper/issues/3966

Example: In the proxy a route with filter chain a() -> b() exists.

b() panics and a() implements errorHandlerFilter interface and return true from HandleErrorResponse().  In this case we should run the filter a().Response(), because we need to cleanup things as expected.

For example scheduler filters like fifo() or lifo() need to decrement the active concurrent requests counter or we will stop requests in the queue, wich would be miss leading.  If we panic in b() and everyone will look at behavior of a(), because we are stuck there caused by not running the cleanup.

### CODE REVIEW

File: proxy/proxy_test.go [hunk 1]
```diff
@@ -1028,27 +1031,58 @@ func TestFilterPanic(t *testing.T) {
...
 	defer s.Close()
 
+	metrics := &metricstest.MockMetrics{}
+	defer metrics.Close()
+	d := 50 * time.Millisecond
+	reg := scheduler.RegistryWith(scheduler.Options{
+		Metrics:                metrics,
+		EnableRouteFIFOMetrics: true,
+		MetricsUpdateTimeout:   d,
+	})
```
Comment (madumalt) [inline proxy/proxy_test.go:1041]:
```suggestion
	reg := scheduler.RegistryWith(scheduler.Options{
		Metrics:                metrics,
		EnableRouteFIFOMetrics: true,
		MetricsUpdateTimeout:   50 * time.Millisecond,
	})
```

Comment (madumalt) [reply proxy/proxy_test.go:1041]: why define a var if we can directly assign it. On the other hand its more readable this way for me.

File: proxy/proxy.go [hunk 2]
```diff
@@ -906,7 +906,7 @@ func WithParams(p Params) *Proxy {
 }
 
 // applies filters to a request
-func (p *Proxy) applyFiltersToRequest(f []*routing.RouteFilter, ctx *context) []*routing.RouteFilter {
+func (p *Proxy) applyFiltersToRequest(f []*routing.RouteFilter, ctx *context, counter *int) []*routing.RouteFilter {
```
Comment (madumalt) [inline proxy/proxy.go:909]: shouldn't the var name be `index` instead of `counter` ?

File: proxy/proxy.go [hunk 3]
```diff
@@ -1246,6 +1247,7 @@ func stack() []byte {
 
 func (p *Proxy) do(ctx *context, parentSpan ot.Span) (err error) {
 	var requestElapsed, responseElapsed time.Duration
+	processedFiltersCounter := 0
```
Comment (madumalt) [inline proxy/proxy.go:1250]: similar to the above comment, shouldn't this be something like `lastProcessedFilterIndex` ?

**Review by madumalt — COMMENTED** [review]
some minor comments, suggestions to change some variable names. The logic seems sound to me!

File: proxy/proxy.go (hunk 2 above)
Comment (szuecs) [reply proxy/proxy.go:909]: No because we count number of filters executed in the request path

File: proxy/proxy.go (hunk 3 above)
Comment (szuecs) [reply proxy/proxy.go:1250]: No, same here and "last" would be misleading

File: proxy/proxy_test.go [hunk 4]
```diff
@@ -1059,6 +1093,16 @@ func TestFilterPanic(t *testing.T) {
 	if err = testLog.WaitFor(msg, 100*time.Millisecond); err != nil {
 		t.Errorf("expected '%s' in logs", msg)
 	}
+
+	// wait for updateMetrics to happen
+	time.Sleep(50*time.Millisecond - time.Since(now))
```
Comment (szuecs) [inline proxy/proxy_test.go]: Here we should use `d`

File: proxy/proxy_test.go (hunk 1 above)
Comment (madumalt) [reply proxy/proxy_test.go:1041]: answer: https://github.com/zalando/skipper/pull/3969#discussion_r3098975802

File: proxy/proxy.go (hunk 2 above)
Comment (madumalt) [reply proxy/proxy.go:909]: I got this whole idea that is more like an index is with this,

https://github.com/zalando/skipper/pull/3969/changes#diff-1d74870266949f1927a500e5f0002617239d3e3cd9bcceee6be014738e5e0f2bR1266

Comment (madumalt) [reply proxy/proxy.go:909]: I approved the PR, if the suggestion doen't make sense, just ignore it :)

**Review by madumalt — APPROVED** [review]

**Comment by szuecs** [comment]
:+1:

File: proxy/proxy.go [hunk 5]
```diff
@@ -1259,6 +1261,10 @@ func (p *Proxy) do(ctx *context, parentSpan ot.Span) (err error) {
 			perr := &proxyError{
 				err: fmt.Errorf("panic caused by: %v", r),
 			}
+
+			if processedFiltersCounter != 0 {
+				p.applyFiltersOnError(ctx, ctx.route.Filters[:processedFiltersCounter])
```
Comment (MustafaSaber) [inline proxy/proxy.go:1266]: What if we have another panic in this call?

Comment (szuecs) [reply proxy/proxy.go:1266]: then we likely panic

**Review by MustafaSaber — APPROVED** [review]
