### PR TITLE
Service unavailable error

### LINKED ISSUE #241: Kubernetes: Skipper throws Internal Server Error for service without endpoints
I created a Kubernetes service and Ingress and the service has no endpoints (wrong label selector):

```
$ http https://myapp-ingress.example.org/
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 22
Content-Type: text/plain; charset=utf-8
Date: Fri, 16 Dec 2016 22:24:39 GMT
X-Content-Type-Options: nosniff

Internal Server Error
```

I think it's because the service has no endpoints:
```
$ zkubectl describe svc myapp
Name:			myapp
Namespace:		default
Labels:			application=myapp
Selector:		<none>
Type:			ClusterIP
IP:			10.3.0.179
Port:			<unset>	80/TCP
Endpoints:		<none>
Session Affinity:	None
```

I would expect Skipper to return HTTP error 503 in that case:

> 503 Service Unavailable
> The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state

### PR DESCRIPTION
**Pull request by aryszka**
return 503 Service Unavailable on errors when connecting to a backend service

Closes #241

### CODE REVIEW

File: proxy/proxy.go [hunk 1]
```diff
@@ -568,10 +569,13 @@ func (p *Proxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 
 			if err != nil {
 				p.metrics.IncErrorsBackend(rt.Id)
-				sendError(w,
-					http.StatusText(http.StatusInternalServerError),
-					http.StatusInternalServerError)
-				p.metrics.MeasureServe(rt.Id, r.Host, r.Method, http.StatusInternalServerError, startServe)
+				code := http.StatusInternalServerError
+				if _, ok := err.(net.Error); ok {
```
Comment (hjacobs) [inline proxy/proxy.go]: not sure what this does and what values `err` can have

**Comment by hjacobs** [comment]
LGTM, but somebody with more insights should probably have a look?

/cc @lmineiro @Raffo

**Comment by lmineiro** [comment]
lgtm
