### PR TITLE
proxy: fix flaky TestAuditLogging

### LINKED ISSUE #2572: Flaky TestAuditLogging
```
--- FAIL: TestAuditLogging (0.00s)
    --- FAIL: TestAuditLogging/on (0.00s)
        upgrade_test.go:427: failed to enable audit log
```

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
The TestAuditLogging could flake because it checks audit log after receiving response message from the connection which may happen before write to audit log by io.MultiWriter has finished.

It could be reproduced via:
```
go test ./proxy -run=TestAuditLogging -count=10000 -failfast
```

This change writes to auditLog before writing to the connection which also would show failed message in the audit log in case write to connection fails.

Fixes #2572

### CODE REVIEW

File: proxy/upgrade_test.go [hunk 1]
```diff
@@ -344,10 +344,9 @@ func TestAuditLogging(t *testing.T) {
 		return func(t *testing.T) {
 			wss := httptest.NewServer(websocket.Handler(func(ws *websocket.Conn) {
 				if _, err := io.Copy(ws, ws); err != nil {
-					t.Fatal(err)
+					t.Error(err)
```
Comment (AlexanderYastrebov) [inline proxy/upgrade_test.go:347]: Avoid "using t.Fatal in a goroutine"

File: proxy/upgrade.go [hunk 2]
```diff
@@ -161,7 +161,7 @@ func (p *upgradeProxy) serveHTTP(w http.ResponseWriter, req *http.Request) {
 	done := make(chan struct{}, 2)
 
 	if p.useAuditLog {
-		copyAsync("backend->request+audit", backendConn, io.MultiWriter(requestHijackedConn, p.auditLogOut), done)
+		copyAsync("backend->request+audit", backendConn, io.MultiWriter(p.auditLogOut, requestHijackedConn), done)
```
Comment (szuecs) [inline proxy/upgrade.go:164]: Does this help or is this unrelated?

Comment (AlexanderYastrebov) [reply proxy/upgrade.go:164]: It is the fix - this way audit log is always written first. I think it also makes sense to have it in the audit log even if subsequent write to connection fails.

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:
