### PR TITLE
Fixes `watch_test` race conditions

### LINKED ISSUE #612: failing build eskipfile TestWatchUpdateRecover
The build of #593 is failing on travis (maybe flaky test, because yesterday it worked without code change in this).

```--- FAIL: TestWatchUpdateRecover (0.04s)
	watch_test.go:93: failed to load route for: /foo
FAIL
FAIL	github.com/zalando/skipper/eskipfile	0.237s
```

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
* Ensures `loggingtest.Logger` always writes to clear return channel (otherwise `Reset` will wait forever)
* Fixes race condition in `createFileWith` between `Create` (truncate) and `WriteString`
* Uses `Fatal` to fail fast

Reproduced/verified with:
```
while true; do go test -race -test.short -count=10 -timeout=10s github.com/zalando/skipper/eskipfile; done
```

Fixes #612

Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

File: logging/loggingtest/logger.go [hunk 1]
```diff
@@ -123,10 +123,7 @@ func New() *Logger {
 				lw.count(req)
 			case c := <-clear:
 				lw.clear()
-				select {
-				case c <- struct{}{}:
-				default:
```
Comment (AlexanderYastrebov) [inline logging/loggingtest/logger.go:128]: https://github.com/zalando/skipper/blob/233e1d33f24e0f3ef062488fbb99bfb187c1cebf/logging/loggingtest/logger.go#L187-L192

Failure sequence:
```
 // Reset(): sends return channel
tl.clear <- ch

// New(): can not send on return channel because 
// the channel has no buffer and there is no receiver, 
// the return channel is lost
select default 

 // Reset(): hangs
<-ch
```
Example https://github.com/zalando/skipper/pull/1552/checks?check_run_id=1261043711

File: eskipfile/watch_test.go [hunk 2]
```diff
@@ -44,15 +45,20 @@ func deleteFile(t *testing.T) {
 }
 
 func createFileWith(content string, t *testing.T) {
-	f, err := os.Create(testWatchFile)
+	tmpfile, err := ioutil.TempFile("", "watch_test-*")
 	if err != nil {
 		t.Fatal(err)
 	}
-	defer f.Close()
+	defer os.Remove(tmpfile.Name())
```
Comment (AlexanderYastrebov) [inline eskipfile/watch_test.go:53]: https://github.com/zalando/skipper/issues/939#issuecomment-509769139
```diff
--- a/eskipfile/watch_test.go
+++ b/eskipfile/watch_test.go
@@ -50,6 +50,8 @@ func createFileWith(content string, t *testing.T) {
        }
        defer f.Close()
 
+       time.Sleep(100 * time.Millisecond)
+
        _, еrr := f.WriteString(content)
        if еrr != nil {
                t.Fatal(еrr)
```
```
$ go test -test.short -count=1 -run TestWatchInitialRecovers  github.com/zalando/skipper/eskipfile
--- FAIL: TestWatchInitialRecovers (0.19s)
    watch_test.go:101: failed to load route for: /foo
FAIL
FAIL    github.com/zalando/skipper/eskipfile    0.197s
FAIL
```

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
thanks man, you are onfire!

**Comment by AlexanderYastrebov** [comment]
@aryszka Lets merge this one maybe? PR builds still stumble upon it

**Comment by aryszka** [comment]
:heart:

**Comment by aryszka** [comment]
:+1:
