### PR TITLE
Checks request context error before roundtrip error

### LINKED ISSUE #1631: Client disconnecting before the request is sent can result in the wrong status code
**Describe the bug**

If a client disconnects before the request is sent, most of the time Skipper recognises it correctly and tracks it with the status code 499:

    [APP]time="2020-12-04T09:54:41Z" level=error msg="client canceled after 64.545424ms, route kube_XXXX with backend network http://XXXX:8080, status code 499: dialing failed false: context canceled, remote host: XXXX, request: \"POST / HTTP/1.1\", user agent: \"\""
    XXXX - - [04/Dec/2020:09:54:41 +0000] "POST / HTTP/1.1" 499 1 "-" "-" 64 XXXX - -

About 10–15% of the time, however, a different code path is triggered and the request is instead tracked as a 503. This can affect application metrics and lead to investigations even though the issue is actually on the client side:

    [APP]time="2020-12-04T09:54:41Z" level=error msg="net.Error during backend roundtrip to http://XXXX:8080: timeout=false temporary=false: readfrom tcp XXXX:59618->XXXX:8080: unexpected EOF"
    [APP]time="2020-12-04T09:54:41Z" level=error msg="error while proxying after 70.344343ms, route kube_XXXX with backend network http://XXXX:8080, status code 503: dialing failed false: readfrom tcp XXXX:59618->XXXX:8080: unexpected EOF, remote host: XXXX, request: \"POST / HTTP/1.1\", user agent: \"\""
    XXXX - - [04/Dec/2020:09:54:41 +0000] "POST / HTTP/1.1" 503 20 "-" "-" 70 XXXX - -

**To Reproduce**

    HOSTNAME=XXXX

    echo "POST / HTTP/1.1
    Host: $HOSTNAME
    Content-Length: 20

    asd" > request

    while sleep 1; do cat request|socat -dd stdio openssl:$HOSTNAME:443,verify=0; done

**Expected behavior**

All of the requests result in a 499.

**Observed behavior**

About 10–15% of the requests instead result in a 503.

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
When client abruptly closes request the context gets `context canceled` error but the roundtrip
may end up with either `unexpected EOF` or the same `context canceled` error nondeterministically.

This change checks request context error before checking roundtrip error.

See https://github.com/zalando/skipper/issues/1631#issuecomment-739110280

Fixes #1631

Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

File: proxy/clienttimeout_test.go [hunk 1]
```diff
@@ -57,3 +58,52 @@ func TestClientTimeout(t *testing.T) {
...
+		if err := postTruncated(addr); err != nil {
+			t.Fatal(err)
+		}
+	}
+
+	// Look for N messages like
+	// 2020/12/05 17:24:00 client canceled after 1.090638ms, route  with backend network http://127.0.0.1:39687, status code 499: dialing failed false: context canceled, remote host: 127.0.0.1, request: "POST / HTTP/1.1", user agent: ""
+	for _, m := range []string{"client canceled after", "status code 499", "context canceled"} {
+		if err = tp.log.WaitForN(m, N, 100*time.Millisecond); err != nil {
+			t.Errorf("expected '%s' %d times, got %d", m, N, tp.log.Count(m))
```
Comment (AlexanderYastrebov) [inline proxy/clienttimeout_test.go:94]: Before the change:
```
$ go test -short -count=1 -run TestClientCancellation github.com/zalando/skipper/proxy
--- FAIL: TestClientCancellation (0.31s)
    clienttimeout_test.go:94: expected 'client canceled after' 100 times, got 44
    clienttimeout_test.go:94: expected 'status code 499' 100 times, got 44
    clienttimeout_test.go:94: expected 'context canceled' 100 times, got 44
FAIL
FAIL    github.com/zalando/skipper/proxy        0.317s
FAIL
```

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:
